Mobile setup
kennedyowusu/portfolio pull request #2
Opened 2022-09-23 09:44 UTC by kennedyowusu

1. Created a new branch with the name mobile_setup
2. Implemented the HTML and CSS for the mobile version of the home page from scratch

2022-09-23 11:30 UTC, Olamarx requested changes
Hi @kennedyowusu, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/zJa9gtkUgYh1wVbm15/giphy.gif"/>

- [ ] Kindly stick to the figma template in terms of font size, width, color and others.
- [ ] The image should be added as background through CSS. Check the inline comment, please.
## Your Design
![image](https://user-images.githubusercontent.com/86200356/191949803-ea925c64-f54a-4d31-a19b-d18c3d9db864.png)
## Figma Design
![image](https://user-images.githubusercontent.com/86200356/191950468-99845acc-2e35-4ea2-b193-e1d4322a29b3.png)


 ## Highlights
- Meaningful commit messages ✔️ 
- All Linters Passed ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 11:30 UTC, Olamarx commented on index.html
> +          srcset=""
- [ ] Kindly add this as a background image through the CSS. Kindly check [here](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) to know how when to use the image and CSS background. Learn how to add the background [here](https://www.w3schools.com/cssref/pr_background-image.asp)

2022-09-24 15:02 UTC, vickymarz requested changes
Hi @kennedyowusu, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 15:02 UTC, vickymarz commented on index.html
> +            />
- [ ] As the previous reviewer has suggested, Kindly add this as a background image through the CSS. Kindly check [here](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) to know how when to use the image and CSS background. Learn how to add the background [here](https://www.w3schools.com/cssref/pr_background-image.asp)

2022-09-24 15:02 UTC, vickymarz commented on index.html
> +          <div class="inner-wrapper">
- [ ] To wrap a list of items, you should use `<ul>` together with` <li>` and not `<div class="inner-wrapper">`

2022-09-24 17:32 UTC, ha-manel approved these changes
# STATUS: APPROVED ✅
## Hi @kennedyowusu 👋

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

<img src="https://media4.giphy.com/media/26DOoDwdNGKAg6UKI/giphy-downsized-medium.gif"/> 

## Highlights:
* Well written PR description ✔️ 
* Proper use of GitHub flow ✔️  
* All tests passed ✔️ 

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 17:34 UTC, merged